import fs from 'node:fs';
import path from 'node:path';
import { toAePath, ensureDir } from '../core/paths.js';

const sameFile = (a, b) => Boolean(a && b) && (process.platform === 'win32' ? path.resolve(a).toLowerCase() === path.resolve(b).toLowerCase() : path.resolve(a) === path.resolve(b));
const inside = (child, dir) => { if (!child || !dir) return false; const rel = path.relative(path.resolve(dir), path.resolve(child)); return Boolean(rel) && !rel.startsWith('..') && !path.isAbsolute(rel); };

/**
 * Who does the project that is open in After Effects belong to?
 *   none  nothing is open (or an empty untitled project): free to use
 *   xoxo  generated by XOXOEDITZ (ownership marker saved in the project, or - for projects made before markers existed -
 *         a file inside the projects folder)
 *   user  anything else: somebody's own work. XOXOEDITZ never modifies or discards it unless the user explicitly says so.
 */
export function classifyProject(status, { projectsDir = null, aepPath = null } = {}) {
  const dirty = Boolean(status?.dirty); const file = status?.file || null;
  const empty = !status?.open || (!file && !(status.numItems > 0) && !dirty);
  const isTarget = sameFile(file, aepPath);
  if (empty) return { kind: 'none', dirty: false, file: null, isTarget: false, reason: 'no project is open' };
  if (status?.owner) return { kind: 'xoxo', dirty, file, isTarget, project: status.owner.project || null, reason: `marked as an XOXOEDITZ project${status.owner.project ? ` ("${status.owner.project}")` : ''}` };
  if (file && inside(file, projectsDir)) return { kind: 'xoxo', dirty, file, isTarget, reason: 'the file lives in the XOXOEDITZ projects folder' };
  return { kind: 'user', dirty, file, isTarget, reason: file ? 'a project XOXOEDITZ did not create' : 'an untitled project XOXOEDITZ did not create' };
}

/** Current After Effects project state + classification (works against hosts that predate project_status). */
export async function projectState(bridge, { projectsDir = null, aepPath = null } = {}) {
  let r = await bridge.call('project_status');
  if (!r.success && r.code === 'UNKNOWN_OP') { const i = await bridge.call('project_info'); r = i.success ? { success: true, data: { open: i.data.numItems > 0 || Boolean(i.data.file), file: i.data.file, untitled: !i.data.file, dirty: i.data.dirty, numItems: i.data.numItems, comps: i.data.comps, owner: null } } : i; }
  if (!r.success) return { success: false, operation: 'project_status', error: r.error, code: r.code, recoverable: true };
  return { success: true, operation: 'project_status', data: { ...r.data, ...classifyProject(r.data, { projectsDir, aepPath }), owner: r.data.owner || null } };
}

const userDirtyMessage = (st) => `After Effects has ${st.file ? `the project "${st.file}"` : 'an untitled project'} open with UNSAVED CHANGES that XOXOEDITZ did not create. It will not modify or discard somebody else's work. Save or close it in After Effects (or run \`xoxo project save\` / \`xoxo project close --save\`), then re-run. To throw those unsaved changes away on purpose, re-run with --discard.`;

/**
 * Make After Effects ready to work on `aepPath` without ever destroying work that is not XOXOEDITZ's to destroy.
 *
 *  open project            action
 *  ----------------------  ---------------------------------------------------------------------------------------
 *  none                    proceed
 *  the target itself       reuse it as it is (dirty or not - nothing is lost)
 *  other, clean            close it (nothing unsaved) and proceed
 *  XOXO, dirty             policy "save" (default): save it (or, if it never had a file, to <projects>/_recovered/) then
 *                          proceed; policy "discard": discard its unsaved changes
 *  user, dirty             REFUSE with an actionable message - unless the caller passed discard:true explicitly
 *
 * `discard` is only ever set by an explicit --discard / discard:true; it is never read from a config file.
 */
export async function prepareProject(bridge, aepPath, { discard = false, projectsDir = null, dirtyPolicy = 'save', recoveryDir = null } = {}) {
  const st = await projectState(bridge, { projectsDir, aepPath });
  if (!st.success) return st;
  const s = st.data; const notes = [];
  const base = { success: true, operation: 'prepare_project', data: { state: s.kind, dirty: s.dirty, file: s.file, action: 'none', notes } };
  if (s.kind === 'none') return base;
  if (s.isTarget) { base.data.action = 'reuse-target'; return base; }
  if (!s.dirty) { base.data.action = 'close-clean'; notes.push(`closed ${s.kind === 'user' ? 'your' : 'the previous XOXOEDITZ'} project ${s.file || '(untitled)'} - it had no unsaved changes`); return base; }
  // dirty and not the target
  if (s.kind === 'user') {
    if (!discard) return { success: false, operation: 'prepare_project', code: 'PROJECT_DIRTY_USER', recoverable: true, error: userDirtyMessage(s), data: { state: s.kind, dirty: true, file: s.file, action: 'refused' } };
    base.data.action = 'discarded-user'; notes.push(`DISCARDED the unsaved changes of ${s.file || 'an untitled project'} because --discard was passed explicitly`); return base;
  }
  // dirty XOXOEDITZ project
  if (discard || dirtyPolicy === 'discard') { base.data.action = 'discarded-xoxo'; notes.push(`discarded the unsaved changes of the XOXOEDITZ project ${s.file || '(untitled)'}${discard ? ' (--discard)' : ' (policy: discard)'}`); return base; }
  if (s.file) {
    const r = await bridge.call('project_save', {});
    if (!r.success) return { success: false, operation: 'prepare_project', code: 'PROJECT_SAVE_FAILED', recoverable: true, error: `could not save the previous XOXOEDITZ project ${s.file}: ${r.error}. Save it in After Effects or pass --discard.`, data: { state: s.kind, dirty: true, file: s.file, action: 'refused' } };
    base.data.action = 'saved-xoxo'; notes.push(`saved the previous XOXOEDITZ project ${s.file} before switching`);
    return base;
  }
  const dir = recoveryDir || path.join(projectsDir || '.', '_recovered'); ensureDir(dir);
  const dest = path.join(dir, `recovered_${new Date().toISOString().replace(/[:.]/g, '-')}.aep`);
  const r = await bridge.call('project_save', { path: toAePath(dest) });
  if (!r.success) return { success: false, operation: 'prepare_project', code: 'PROJECT_SAVE_FAILED', recoverable: true, error: `could not save the unsaved XOXOEDITZ project to ${dest}: ${r.error}. Save it in After Effects or pass --discard.`, data: { state: s.kind, dirty: true, file: null, action: 'refused' } };
  base.data.action = 'saved-xoxo-recovery'; notes.push(`saved the unsaved XOXOEDITZ project to ${dest}`);
  return base;
}

/** Open an existing .aep (after prepareProject). `created:false`. Marks nothing - the project already exists. */
export async function openProject(bridge, aepPath, opts = {}) {
  const prep = await prepareProject(bridge, aepPath, opts);
  if (!prep.success) return prep;
  const mustDiscard = ['discarded-user', 'discarded-xoxo'].includes(prep.data.action);
  const r = await bridge.call('project_open', { path: toAePath(aepPath), discard: mustDiscard });
  if (!r.success) return { ...r, operation: 'open_project' };
  return { success: true, operation: 'open_project', data: { created: false, ...r.data, prepare: prep.data } };
}

/**
 * Open the project's .aep if it exists, otherwise create, mark and save a fresh one. Idempotent. State handling
 * (unsaved changes, foreign projects) is prepareProject's job; `discard` must be an explicit request.
 */
export async function openOrCreateProject(bridge, aepPath, { discard = false, projectsDir = null, name = null, dirtyPolicy = 'save', recoveryDir = null } = {}) {
  const ping = await bridge.ping();
  if (!ping.success) return { success: false, operation: 'open_project', error: ping.error, recoverable: true, code: ping.code };
  ensureDir(path.dirname(aepPath));
  const prep = await prepareProject(bridge, aepPath, { discard, projectsDir, dirtyPolicy, recoveryDir });
  if (!prep.success) return { ...prep, operation: 'open_project' };
  const target = toAePath(aepPath);
  const allow = ['discarded-user', 'discarded-xoxo'].includes(prep.data.action); // only an explicit discard (or the XOXO discard policy) lets the host drop unsaved changes
  const pname = name || path.basename(aepPath, '.aep');
  if (fs.existsSync(aepPath)) {
    const r = await bridge.call('project_open', { path: target, discard: allow });
    if (!r.success) return { ...r, operation: 'open_project' };
    if (!r.data?.reused) await markOwned(bridge, pname, aepPath); // projects from before ownership markers get one the first time they are opened
    return { success: true, operation: 'open_project', data: { created: false, ae: ping.data, ...r.data, prepare: prep.data } };
  }
  const n = await bridge.call('project_new', { discard: allow });
  if (!n.success) return { ...n, operation: 'open_project' };
  await bridge.call('project_mark', { project: pname });
  const s = await bridge.call('project_save', { path: target });
  if (!s.success) return { ...s, operation: 'open_project' };
  return { success: true, operation: 'open_project', data: { created: true, ae: ping.data, file: s.data.file, prepare: prep.data } };
}

async function markOwned(bridge, name, aepPath) {
  const m = await bridge.call('project_mark', { project: name });
  if (m.success) await bridge.call('project_save', { path: toAePath(aepPath) });
}

/** `xoxo project close`: closing is never implicit. XOXOEDITZ projects are saved by default; somebody else's need an explicit save or discard. */
export async function closeProject(bridge, { save = false, discard = false, projectsDir = null } = {}) {
  const st = await projectState(bridge, { projectsDir });
  if (!st.success) return st;
  const s = st.data;
  if (s.kind === 'none') return { success: true, operation: 'close_project', data: { closed: false, note: 'no project is open' } };
  if (save && discard) return { success: false, operation: 'close_project', code: 'BAD_ARGS', error: 'pass either --save or --discard, not both', recoverable: false };
  if (s.dirty && s.kind === 'user' && !save && !discard) return { success: false, operation: 'close_project', code: 'PROJECT_DIRTY_USER', recoverable: true, error: `${userDirtyMessage(s).replace(/ Save or close it.*$/, '')} Choose: \`xoxo project close --save\` (saves your changes first) or \`xoxo project close --discard\` (throws them away).`, data: s };
  const doSave = save || (s.kind === 'xoxo' && s.dirty && !discard);
  if (doSave && !s.file) return { success: false, operation: 'close_project', code: 'NO_PROJECT_FILE', recoverable: true, error: 'the open project was never saved, so there is nowhere to save it; use `xoxo project save --as <file.aep>` first or pass --discard', data: s };
  const r = await bridge.call('project_close', { save: doSave });
  return r.success ? { success: true, operation: 'close_project', data: { closed: true, file: s.file, saved: doSave, discarded: s.dirty && !doSave, kind: s.kind } } : { ...r, operation: 'close_project' };
}

/** `xoxo project save`: an explicit command, so it may save any open project (it only persists what is already there). */
export async function saveOpenProject(bridge, { as = null, projectsDir = null } = {}) {
  const st = await projectState(bridge, { projectsDir });
  if (!st.success) return st;
  if (st.data.kind === 'none') return { success: true, operation: 'save_project', data: { saved: false, note: 'no project is open' } };
  if (!st.data.file && !as) return { success: false, operation: 'save_project', code: 'NO_PROJECT_FILE', recoverable: true, error: 'the open project has never been saved; pass --as <file.aep>', data: st.data };
  const r = await bridge.call('project_save', as ? { path: toAePath(path.resolve(as)) } : {});
  return r.success ? { success: true, operation: 'save_project', data: { saved: true, file: r.data.file, kind: st.data.kind } } : { ...r, operation: 'save_project' };
}

export async function saveProject(bridge, aepPath) {
  const r = await bridge.call('project_save', { path: toAePath(aepPath) });
  return { ...r, operation: 'save_project' };
}

/**
 * Save and keep a numbered copy in versions/ (After Effects has no scripted "Save a Copy", but a saved
 * .aep is a single file, so copying it is a safe checkpoint).
 */
export async function checkpoint(bridge, paths, label = 'checkpoint') {
  const s = await saveProject(bridge, paths.aep);
  if (!s.success) return s;
  ensureDir(paths.versions);
  const existing = fs.readdirSync(paths.versions).filter((f) => /_v\d{3}/.test(f)).length;
  const n = String(existing + 1).padStart(3, '0');
  const safe = label.replace(/[^\w-]+/g, '_');
  const dest = path.join(paths.versions, `${path.basename(paths.aep, '.aep')}_v${n}_${safe}.aep`);
  try { fs.copyFileSync(paths.aep, dest); } catch (e) { return { success: false, operation: 'checkpoint', error: e.message, recoverable: true }; }
  return { success: true, operation: 'checkpoint', data: { file: dest, version: Number(n) } };
}
