// Reference for every host operation (jsx/*.jsx). A test fails if an op is added without an entry here.
// Times are seconds. Colours are "#rrggbb". Layers/comps are addressed by NAME (indices also accepted for layers).

export const OPS_DOC = {
  ping: { group: 'project', args: '{}', returns: 'AE version, build, OS, project state, scriptsMayWriteFiles', doc: 'Connectivity + environment probe. Run first.' },
  project_info: { group: 'project', args: '{}', returns: '{file, dirty, numItems, comps[]}', doc: 'Current project summary.' },
  project_new: { group: 'project', args: '{discard?}', doc: 'New empty project. Refuses if unsaved changes unless discard:true.' },
  project_open: { group: 'project', args: '{path, discard?}', doc: 'Open an .aep (no-op when already open).' },
  project_save: { group: 'project', args: '{path?}', doc: 'Save (Save As when path is given).' },
  folder_ensure: { group: 'project', args: '{path:"A/B"}', doc: 'Create nested project-panel folders if missing.' },
  import_ensure: { group: 'project', args: '{path, name?, folder?, sequence?}', doc: 'Idempotent import: reuses an existing item pointing at the same file; renames to `name`.' },
  comp_ensure: { group: 'comp', args: '{name,width,height,fps,duration,pixelAspect?,bg?,folder?,reset?}', doc: 'Create or update a composition; reset:true removes all layers.' },
  comp_set: { group: 'comp', args: '{comp,duration?,motionBlur?,bg?,shutterAngle?}', doc: 'Adjust comp settings.' },
  comp_set_work_area: { group: 'comp', args: '{comp,start,duration}', doc: 'Set the work area.' },
  layers_clear: { group: 'comp', args: '{comp}', doc: 'Remove every layer in a comp.' },
  layers_remove: { group: 'comp', args: '{comp,names[],prefix?}', doc: 'Remove layers by name (missing names ignored). Used to make every build step idempotent.' },
  marker_add: { group: 'comp', args: '{comp,time,comment?,duration?,layer?}', doc: 'Comp or layer marker.' },
  layer_add_footage: { group: 'layer', args: '{comp,item,name,start?,end?,sourceIn?,speed?,fit?:"cover"|"contain",hideVideo?,opacity?,threeD?,blend?}', doc: 'Add an imported item or comp as a layer. `start/end` are comp times; `sourceIn` is the source in-point; speed 2 = twice as fast. Returns baseScale.' },
  layer_add_solid: { group: 'layer', args: '{comp,name,color?,width?,height?,start?,end?,opacity?,position?}', doc: 'Solid layer.' },
  layer_add_null: { group: 'layer', args: '{comp,name,start?,end?,position?}', doc: 'Null object.' },
  layer_add_adjustment: { group: 'layer', args: '{comp,name,start?,end?,duration?,opacity?}', doc: 'Adjustment layer (effects apply to layers below).' },
  layer_add_text: { group: 'layer', args: '{comp,name,text,size?,font?(PostScript name),color?,stroke?,strokeWidth?,justify?:"left"|"center"|"right",tracking?,leading?,allCaps?,box?:[w,h],position?,start?,end?,opacity?}', doc: 'Text layer. "\\n" becomes a paragraph break.' },
  layer_add_shape: { group: 'layer', args: '{comp,name,shapes:[{type:"rect"|"ellipse"|"line"|"polyline",size?,points?,fill?,stroke?,strokeWidth?,roundness?,trim?,position?}],position?,start?,end?}', doc: 'Shape layer built from vector primitives.' },
  layer_add_camera: { group: 'layer', args: '{comp,name,center?}', doc: 'Camera (makes 3D layers render with perspective).' },
  layer_add_light: { group: 'layer', args: '{comp,name,center?,intensity?}', doc: 'Light.' },
  layer_set: { group: 'layer', args: '{comp,layer,props:{name,enabled,audioEnabled,solo,shy,locked,threeD,motionBlur,label,blend,parent,startTime,inPoint,outPoint,stretch,comment}}', doc: 'Change layer switches/timing.' },
  layer_move: { group: 'layer', args: '{comp,layer,to:"top"|"bottom"|{before:name}|{after:name}}', doc: 'Reorder.' },
  layers_reorder: { group: 'layer', args: '{comp,order:[names bottom->top]}', doc: 'Set z-order: each named layer is moved to the front in turn, so the last ends on top.' },
  layer_remove: { group: 'layer', args: '{comp,layer}', doc: 'Delete one layer.' },
  track_matte: { group: 'layer', args: '{comp,layer,matte,type:"alpha"|"alphaInverted"|"luma"|"lumaInverted"}', doc: 'Track matte.' },
  mask_add: { group: 'layer', args: '{comp,layer,rect:[l,t,w,h],shape?:"rect"|"ellipse",inverted?,feather?,name?}', doc: 'Add a mask.' },
  text_set: { group: 'layer', args: '{comp,layer,text?,size?,color?}', doc: 'Edit text content/style.' },
  text_reveal: { group: 'anim', args: '{comp,layer,mode:"typewriter"|"fade_up"|"tracking_in",start,duration,offset?,tracking?,unit?:"characters"|"words"}', doc: 'Per-character text animator (range selector sweep).' },
  set_property: { group: 'anim', args: '{comp,layer,prop,value}', doc: 'Set a property. prop = position|scale|rotation|opacity|anchor|audioLevels|timeRemap|sourceText or a "Group/Name" path of match/display names.' },
  keyframes: { group: 'anim', args: '{comp,layer,prop,keys:[{t,v,hold?,ease?}],ease?:"linear"|"easeOut"|"easeIn"|"easeInOut",clear?}', doc: 'Keyframe a property; ease applies between consecutive keys. clear:false appends.' },
  time_remap: { group: 'anim', args: '{comp,layer,keys:[{t,src}],start?,end?,frameBlend?:"none"|"mix"|"pixel",motionBlur?}', doc: 'Enable Time Remap and set comp-time -> source-time keyframes (variable speed, freezes, reverse). Stills/solids are refused.' },
  keys_clear: { group: 'anim', args: '{comp,layer,prop}', doc: 'Remove keyframes and expression from a property.' },
  expression: { group: 'anim', args: '{comp,layer,prop,expression}', doc: 'Set an expression; fails (and clears it) if the expression engine reports an error.' },
  effect_available: { group: 'effects', args: '{matchNames[]}', returns: '{matchName: true|false|null}', doc: 'Is this effect installed? null = host cannot tell.' },
  list_effects: { group: 'effects', args: '{}', doc: 'Every installed effect {displayName, matchName, category}.' },
  list_fonts: { group: 'effects', args: '{}', doc: 'Installed fonts with PostScript names (AE 24.0+).' },
  layer_effect_add: { group: 'effects', args: '{comp,layer,matchName,name?,tag?,params?:{nameOrMatchName:value}}', doc: 'Add an effect. tag prefixes its name "XOXO:<tag>:" so it can be removed. Fails with EFFECT_UNAVAILABLE if not installed.' },
  effect_param_keys: { group: 'effects', args: '{comp,layer,effect(name on layer),param,keys:[{t,v}]}', doc: 'Keyframe an effect parameter.' },
  effects_remove_tag: { group: 'effects', args: '{comp,layer,tag}', doc: 'Remove effects added with this tag.' },
  rq_templates: { group: 'render', args: '{}', returns: '{renderSettings[], outputModules[]}', doc: 'Render settings / output module templates available on this install.' },
  rq_add: { group: 'render', args: '{comp,output,renderSettings?,outputModule?,start?,duration?}', doc: 'Add a render-queue item.' },
  rq_list: { group: 'render', args: '{}', doc: 'Render queue contents.' },
  rq_clear: { group: 'render', args: '{}', doc: 'Empty the render queue.' },
  rq_queue_ame: { group: 'render', args: '{start?}', doc: 'Send the queue to Adobe Media Encoder.' },
  inspect: { group: 'qa', args: '{layers?,bounds?,comps?[]}', doc: 'Full read-only dump of items, comps, layers (kind, timing, effects, text, bounds, audio levels) and render queue.' },
  batch: { group: 'meta', args: '{units:[{id,ops:[{op,args}]}],stopOnError?}', doc: 'Run many ops in one round trip. A unit stops at its first failure; other units continue.' },
  raw_eval: { group: 'meta', args: '{code}', doc: 'Arbitrary ExtendScript. DISABLED unless "allowRawEval": true in xoxo.config.json. Prefer typed ops.' },
};
