#!/usr/bin/env node
// Generates the reference tables that must never drift from the code: edit types, the effect registry, shot
// templates, text kinds, camera rigs, velocity profiles, colour looks. `node scripts/gen-docs.js` rewrites them;
// tests/docs.test.js fails when the committed files are stale.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { EDIT_TYPES } from '../src/edit-types/index.js';
import { REGISTRY } from '../src/effects/registry.js';
import { TEMPLATES } from '../src/compositing/templates.js';
import { TEXT_KINDS } from '../src/typography/engine.js';
import { RIGS } from '../src/camera/rigs.js';
import { VELOCITY_PROFILES } from '../src/velocity/profiles.js';
import { LOOKS } from '../src/color/looks.js';
import { PRIMITIVES } from '../src/motion/primitives.js';
import { TRANSITION_META } from '../src/transitions/entries.js';
import { SPECS, COMMON } from '../src/benchmark/specs.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const row = (cells) => `| ${cells.map((c) => String(c ?? '').replace(/\|/g, '/').replace(/\n/g, ' ')).join(' | ')} |`;
const table = (head, rows) => [row(head), row(head.map(() => '---')), ...rows.map(row)].join('\n');
const HEADER = '<!-- GENERATED by scripts/gen-docs.js from the code - do not edit by hand; run `node scripts/gen-docs.js` -->\n';

export function generate() {
  const out = {};

  out['docs/EDIT_TYPES.md'] = `${HEADER}# Edit types

An edit type is a **behaviour profile**, not a template. It sets how fast the piece cuts, whether it ramps speed, how the
camera behaves, which transitions it trusts, how much type and sound design it wants and which colour treatment it uses.
The Director combines the profile with your prompt, \`edit.config.json\`, your assets and the library
(precedence: type < intensity < edit.config.json < prompt < explicit override; the decision trail is saved in
\`plan.json › directive.sources\`).

Choose one with \`--type\`, \`"type"\` in edit.config.json, or just describe it in the prompt ("make a velocity edit").

${table(['Type', 'Aliases', 'Feels like', 'Shot length (s)', 'Camera rig', 'Velocity profile', 'Colour', 'Transition vocabulary', 'Type animations'], Object.values(EDIT_TYPES).map((t) => [`**${t.id}**`, t.aliases.join(', '), t.description, t.pacing.shotSeconds.join('–'), t.camera.rig, t.velocity.profile || '—', t.color, t.transitions.palette.map((p) => p.type).join(', '), t.typography.animations.join(', ')]))}

## Dials (0–1)

${table(['Type', 'intensity', 'cutFrequency', 'velocity', 'speedVariation', 'camera', 'motionBlur', 'effects', 'sfx', 'transitions', 'text', 'color', 'impact', 'beatSync', 'depth', 'music'], Object.values(EDIT_TYPES).map((t) => [t.id, ...['intensity', 'cutFrequency', 'velocity', 'speedVariation', 'camera', 'motionBlur', 'effects', 'sfx', 'transitions', 'text', 'color', 'impact', 'beatSync', 'depth', 'music'].map((d) => t.dials[d])]))}

## Shot templates each type favours (weights)

${table(['Type', ...Object.keys(TEMPLATES)], Object.values(EDIT_TYPES).map((t) => [t.id, ...Object.keys(TEMPLATES).map((k) => t.shots[k] ?? 0)]))}
`;

  const cat = {};
  for (const [id, d] of Object.entries(REGISTRY)) (cat[d.category] ||= []).push([id, d]);
  out['docs/EFFECTS.md'] = `${HEADER}# Effects, transitions, looks and text animations

Every visual technique is an **effect id** with an ordered chain of implementations, best first. The resolver picks the
best one this machine can run (installed effects are asked of After Effects itself); the last link of every chain needs
nothing, so a missing plugin degrades the result and is reported, but never blocks the edit. \`xoxo effects\` prints the
chains for *your* machine.

${Object.entries(cat).map(([c, list]) => `## ${c}\n\n${table(['Id', 'What it does', 'Fallback chain (quality)', 'Needs'], list.map(([id, d]) => [`\`${id}\``, d.description, [...d.implementations].sort((a, b) => b.quality - a.quality).map((i) => `${i.id} (${i.quality})`).join(' → '), [...new Set(d.implementations.flatMap((i) => (i.requires?.effects || []).map((e) => e.displayName || e.matchName)))].join(', ') || 'nothing']))}\n`).join('\n')}
## Shot-transition vocabulary

${table(['Type', 'Family', 'Sound role', 'Min shot (s)', 'Moves the camera?'], Object.entries(TRANSITION_META).map(([k, m]) => [k, m.family, m.sfx || '—', m.minShot, m.motionHeavy ? 'yes (composed into the shot\'s camera track)' : 'no']))}
`;

  out['docs/SHOT_TEMPLATES.md'] = `${HEADER}# Shot templates, type kinds, camera rigs and motion primitives

## Shot templates (compositing)

${table(['Template', 'Implemented', 'Needs', 'What it is'], Object.entries(TEMPLATES).map(([k, t]) => [`**${k}**`, t.implemented ? 'yes' : '**no (TODO)**', [t.assets ? `${t.assets} asset` : 'no asset', t.needsSubject && 'a detected subject', t.needsText && 'text', t.needsStat && 'a stat', t.needsCallout && 'callout text', t.wantsSecond && 'a second asset (optional)', t.minDur && `≥ ${t.minDur}s`].filter(Boolean).join(', '), t.doc]))}

## Text kinds

${table(['Kind', 'Size (× frame height)', 'Default anchor', 'Max words', 'Case', 'Animations it may use'], Object.entries(TEXT_KINDS).map(([k, t]) => [k, t.size, t.pos.join(', '), t.maxWords, t.caseMode, t.anims.join(', ')]))}

## Camera rigs

${table(['Rig', 'Character', 'Amount (fraction of frame)', 'Max overscan', 'Moves'], Object.values(RIGS).map((r) => [`**${r.id}**`, r.doc, r.amount.join('–'), r.maxLift, r.moves.map((m) => (typeof m === 'function' ? m().name : m.name)).join(', ')]))}

## Motion primitives (composable into one keyframe track)

${table(['Primitive', 'Holds its end pose', 'What it does'], Object.entries(PRIMITIVES).map(([k, p]) => [k, p.hold ? 'yes' : 'no', p.doc]))}

## Velocity profiles

${table(['Profile', 'Speed range', 'Ramp length (s)', 'Typical shot (s)', 'Impact every (s)', 'Reverse chance'], Object.entries(VELOCITY_PROFILES).map(([k, p]) => [k, `${p.minSpeed}×–${p.maxSpeed}×`, p.rampDur.join('–'), p.shotSeconds.join('–'), p.impactEvery, p.reverse]))}

## Colour looks

${table(['Look', 'Character', 'Shadows → highlights', 'Saturation', 'Contrast'], Object.entries(LOOKS).map(([k, l]) => [k, l.doc, `${l.shadow} → ${l.highlight}`, l.sat, l.contrast]))}
`;
  // creative QA codes, read from the check sources so the list cannot drift
  const codes = [];
  for (const f of ['src/creative-qa/plan-checks.js', 'src/creative-qa/render-checks.js']) {
    const src = fs.readFileSync(path.join(root, f), 'utf8');
    for (const m of src.matchAll(/issue\('([a-z]+)',\s*'([A-Z_]+)',\s*('(?:error|warning|info)'|[^,]+?),\s*(`[^`]*`|'[^']*')/g)) codes.push([m[1], m[2], m[3].replace(/'/g, '').length > 8 ? 'error or warning (depends on the edit)' : m[3].replace(/'/g, ''), m[4].replace(/^[`']|[`']$/g, '').replace(/\$\{[^}]*\}/g, '…')]);
  }
  out['docs/CREATIVE_QA_CODES.md'] = `${HEADER}# Creative QA findings

Every finding has a stable code, a category (it feeds that category's score) and a severity. Errors fail the critique;
warnings and infos lower the score. Messages name the shot or metric behind them.

${table(['Category', 'Code', 'Severity', 'Example message'], codes)}
`;

  out['docs/BENCHMARK_CHECKLISTS.md'] = `${HEADER}# Benchmark checklists

Each criterion is evaluated against what was actually produced. **pass**, **fail**, or **skipped** (with the reason;
render criteria are always skipped on the simulator).

## Every benchmark

${table(['Id', 'Criterion'], COMMON.map((c) => [`\`${c.id}\``, c.label]))}

${Object.values(SPECS).map((s) => `## ${s.id} — ${s.title}\n\n> ${s.prompt}\n\n\`\`\`json\n${JSON.stringify(s.config, null, 2)}\n\`\`\`\n\n${table(['Id', 'Criterion'], s.criteria.map((c) => [`\`${c.id}\``, c.label]))}\n`).join('\n')}
`;
  return out;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const files = generate();
  for (const [rel, text] of Object.entries(files)) { fs.writeFileSync(path.join(root, rel), text); console.log(`wrote ${rel} (${text.length} bytes)`); }
}
